name: Weekly cron

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_CRON: 'true'

jobs:

  tests_more_architectures:

    # The following architectures are emulated and are therefore slow, so
    # we include them just in the weekly cron. These also serve as a test
    # of using system libraries and using pytest directly.

    runs-on: linux-arm64
    name: Python 3.12

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up dependencies
        run: |
            apt-get update -q -y
            apt-get install -q -y gnupg2
            # Add test-support repository for wcslib8
            echo "deb http://ppa.launchpadcontent.net/astropy/test-support/ubuntu lunar main" > /etc/apt/sources.list.d/test-support.list
            gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv CC75F07B3EF41EFC
            gpg --export --armor CC75F07B3EF41EFC | tee /etc/apt/trusted.gpg.d/test-support.asc
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends \
                                  git \
                                  g++ \
                                  pkg-config \
                                  python3 \
                                  python3-erfa \
                                  python3-extension-helpers \
                                  python3-jinja2 \
                                  python3-numpy \
                                  python3-pytest-astropy \
                                  python3-setuptools-scm \
                                  python3-yaml \
                                  python3-venv \
                                  python3-wheel \
                                  python3-tox \
                                  wcslib-dev

      - name: Diagnostics
        run: |
            uname -a
            echo "LONG_BIT="$(getconf LONG_BIT)
            python3 -m venv --system-site-packages tests

      - name: Run tests
        run: |
            tox -e test
